CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, login_name text NOT NULL, display_name text NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK (role IN ('BOSS','OPERATOR')), account_status text NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','DISABLED')), must_change_password boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS users_login_unique ON users (lower(login_name));
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf_token text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS login_attempts (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, login_name text NOT NULL, source text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS login_attempt_window ON login_attempts(created_at, login_name, source);
CREATE TABLE IF NOT EXISTS merchant_accounts (id uuid PRIMARY KEY, name text NOT NULL, platform text NOT NULL, enabled boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS merchant_account_name ON merchant_accounts(lower(name));
CREATE TABLE IF NOT EXISTS dictionaries (id uuid PRIMARY KEY, kind text NOT NULL CHECK(kind IN ('customer-tag','product-category','product-tag','asset-category','asset-tag')), name text NOT NULL, archived_at timestamptz, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(kind,name));
CREATE SEQUENCE IF NOT EXISTS customer_numbers START 10001;
CREATE TABLE IF NOT EXISTS customers (id uuid PRIMARY KEY, customer_no text NOT NULL UNIQUE DEFAULT ('C' || nextval('customer_numbers')), owner_id uuid NOT NULL REFERENCES users(id), merchant_account_id uuid NOT NULL REFERENCES merchant_accounts(id), document jsonb NOT NULL, archived_at timestamptz, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS customers_owner_updated ON customers(owner_id,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS customers_status ON customers(owner_id,(document->>'status'));
CREATE INDEX IF NOT EXISTS customers_followup ON customers(owner_id,(document->>'nextFollowupAt'));
CREATE INDEX IF NOT EXISTS customers_deal ON customers(owner_id,(document->>'lastDealAt'));
CREATE INDEX IF NOT EXISTS customers_interests ON customers USING gin ((document->'productIds'));
CREATE TABLE IF NOT EXISTS followups (id uuid PRIMARY KEY, customer_id uuid NOT NULL REFERENCES customers(id), actor_id uuid NOT NULL REFERENCES users(id), document jsonb NOT NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS followups_customer ON followups(customer_id,created_at DESC);
CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY, sku text NOT NULL UNIQUE, document jsonb NOT NULL, archived_at timestamptz, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS products_category ON products((document->>'categoryId'));
CREATE SEQUENCE IF NOT EXISTS order_numbers START 10001;
CREATE TABLE IF NOT EXISTS orders (id uuid PRIMARY KEY, order_no text NOT NULL UNIQUE DEFAULT ('YJ' || to_char(now(),'YYYYMMDD') || nextval('order_numbers')), customer_id uuid NOT NULL REFERENCES customers(id), status text NOT NULL DEFAULT '待付款' CHECK(status IN ('待付款','已付款','取消付款')), type text NOT NULL CHECK(type IN ('正常','退货','维修')), order_date date NOT NULL, paid_at timestamptz, total_incl_tax numeric(18,2) NOT NULL CHECK(total_incl_tax>=0 AND total_incl_tax<=999999999999.99), external_source text, external_order_no text, document jsonb NOT NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS orders_external_unique ON orders(external_source,external_order_no) WHERE external_source IS NOT NULL AND external_order_no IS NOT NULL;
CREATE INDEX IF NOT EXISTS orders_customer_date ON orders(customer_id,order_date DESC,id);
CREATE INDEX IF NOT EXISTS orders_payment ON orders(status,paid_at);
CREATE TABLE IF NOT EXISTS payment_changes (id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES orders(id), actor_id uuid NOT NULL REFERENCES users(id), previous_status text NOT NULL, next_status text NOT NULL, amount numeric(18,2) NOT NULL, paid_at timestamptz, payment_note text NOT NULL DEFAULT '', reason text NOT NULL DEFAULT '', previous_value jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS payments_order ON payment_changes(order_id,created_at DESC);
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY, actor_id uuid REFERENCES users(id), entity_type text NOT NULL, entity_id uuid NOT NULL, operation text NOT NULL, changes jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_created ON audit_events(created_at DESC,id);
