export const fieldLabels: Record<string, string> = {
  before: '修改前',
  after: '修改后',
  from: '原值',
  to: '新值',
  reason: '原因',
  ownerId: '负责人',
  ownerName: '负责人',
  status: '状态',
  paidAt: '付款时间',
  lastDealAt: '最近成交时间',
  name: '名称',
  displayName: '姓名',
  role: '角色',
  accountStatus: '账号状态',
  amount: '金额',
  version: '版本',
  changes: '变更',
  count: '数量',
  source: '来源',
  customerId: '客户编号',
  createdCount: '新增数量',
  kind: '对象',
  paymentNote: '付款备注',
  receivingAccount: '收款账号',
  previousReceivingAccount: '原收款账号',
  loginName: '账号',
  password: '密码',
  currentPassword: '当前密码',
  newPassword: '新密码',
  companyName: '企业名称',
  taxId: '税号',
  companyPhone: '公司电话',
  companyAddress: '公司地址',
  bankName: '开户行',
  bankAccount: '银行账号',
  contactName: '联系人',
  contactPhone: '联系电话',
  deliveryAddress: '收货地址',
  taobaoId: '淘宝号',
  wechatId: '微信号',
  wechatName: '微信名称',
  douyinId: '抖音号',
  merchantAccountId: '所属账号',
  merchantAccountName: '所属账号',
  sourceChannel: '来源渠道',
  productIds: '关联产品',
  tagIds: '标签',
  assetIds: '关联资料',
  nextFollowupAt: '下次跟进',
  customerNo: '客户编号',
  sku: '产品编号 / SKU',
  model: '规格型号',
  unit: '单位',
  priceExTax: '不含税单价',
  categoryId: '分类',
  categoryName: '分类',
  recipientName: '收货人',
  recipientPhone: '联系方式',
  recipientAddress: '收货地址',
  invoiceRequired: '是否开票',
  note: '备注',
  type: '订单类型',
  orderDate: '下单日期',
  orderNo: '订单编号',
  originalOrderId: '原订单',
  externalSource: '外部来源',
  externalOrderNo: '外部原单号',
  freightFee: '运费',
  packagingFee: '包装费',
  taxFee: '税费',
  taxRate: '税率',
  taxFeeMode: '税费计算方式',
  calculatedTaxFee: '计算税费',
  calculatedTotalInclTax: '计算总金额',
  totalInclTaxOverride: '调整后总金额',
  attachmentIds: '运单图片',
  goodsTotal: '商品总金额',
  totalExTax: '不含税总计',
  totalInclTax: '含税总计',
  lines: '产品明细',
  shipments: '物流信息',
  carrier: '物流公司',
  freightPayment: '运费要求',
  trackingNo: '物流单号',
  productId: '产品',
  quantity: '数量',
  unitPriceExTax: '不含税单价',
  lineTotal: '明细金额',
  description: '资料说明',
  mediaType: '文件类型',
  bytes: '文件大小',
  originalName: '原文件名',
  file: '文件',
  metadata: '资料信息',
  content: '跟进内容',
  occurredAt: '跟进时间',
  contactChannel: '联系渠道',
  platform: '平台',
  enabled: '启用状态',
  archivedAt: '归档时间',
  createdAt: '创建时间',
  updatedAt: '更新时间',
  oldOwnerId: '原负责人',
  newOwnerId: '新负责人',
  orderCount: '关联订单数',
  followupCount: '跟进记录数',
  filename: '文件名',
  rowCount: '数据行数',
  validRows: '有效行数',
  expectedNew: '预计新增',
  category: '分类',
  tags: '标签',
  products: '关联产品',
  userId: '账号',
  actorId: '操作者',
  assetId: '资料',
  id: '记录编号',
  oldVersion: '原版本',
  newVersion: '新版本',
  changed: '修改字段',
  archived: '已归档',
  versionId: '文件版本',
  total: '总数',
  owner: '负责人',
};

export function validationMessage(body: {
  message?: unknown;
  fieldErrors?: Record<string, unknown>;
}) {
  const errors = Object.entries(body.fieldErrors || {});
  if (errors.length)
    return errors
      .map(([field, values]) => {
        const messages = Array.isArray(values) ? values : [values];
        const text = messages
          .map((message) =>
            /[\u3400-\u9fff]/.test(String(message)) ? String(message) : '格式不正确',
          )
          .filter((message, index, all) => all.indexOf(message) === index)
          .join('、');
        return `${fieldLabels[field] || '字段'}：${text}`;
      })
      .join('；');
  return Array.isArray(body.message)
    ? body.message.join('；')
    : typeof body.message === 'string'
      ? body.message
      : '';
}
